export const MAX_WORKSPACE_EDGE_PX = 800;
export const MAX_WORKSPACE_AREA_PX = MAX_WORKSPACE_EDGE_PX * MAX_WORKSPACE_EDGE_PX;

export const MAX_RENDER_CANVAS_EDGE_PX = 8192;
export const MAX_RENDER_CANVAS_AREA_PX = 16_000_000;
